### ISSUE TITLE
Clipping Box renders masked material as translucent with MSAA

### ISSUE THREAD

**Issue by juanwinsor** [microsoft/MixedReality-GraphicsTools-Unreal#24]
I have a simple material, set to masked with Opacity Mask Clip Value set to 0 so it doesn't feather.

![clippingmaterial](https://user-images.githubusercontent.com/2079413/166686911-ba1779a1-2013-45ba-8214-a59db694e033.png)

I am using forward rendering with MSAA, this is the result.  It works fine with other AA options

![clippingresult](https://user-images.githubusercontent.com/2079413/166686998-e849e7e1-e516-4de2-aa5a-6eadd75bb518.png)

**Comment by Cameron-Micka** [comment]
Hi @juanwinsor, thank you for reporting this. I was able to reproduce this locally as well when enabling MSAA in the editor. 

My guess is that Unreal Engine enabled "alpha to coverage" recently to help reduce aliasing on cutout materials.

A quick fix for this is to multiply the output of the clipping functions by a constant (like 100): 
![image](https://user-images.githubusercontent.com/13305729/166841533-0300892d-d677-401a-8dea-642226cc498d.png)

A better fix is to rescale alpha by partial derivative like so:
![image](https://user-images.githubusercontent.com/13305729/166841611-1f6db795-4d63-419f-9a21-3b971cfd312b.png)

I'll try an incorporate this rescale as the default behavior in the next release of Graphics Tools. 😊
